In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/datasets/jessicali9530/kuc-hackathon-winter-2018/drugsComTest_raw.csv
/kaggle/input/datasets/jessicali9530/kuc-hackathon-winter-2018/drugsComTrain_raw.csv

In [2]:
dataset = pd.read_csv('/kaggle/input/datasets/jessicali9530/kuc-hackathon-winter-2018/drugsComTrain_raw.csv')

In [3]:
dataset

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""It has no side effect, I take it in combinati...",9,20-May-12,27
1,95260,Guanfacine,ADHD,"""My son is halfway through his fourth week of ...",8,27-Apr-10,192
2,92703,Lybrel,Birth Control,"""I used to take another oral contraceptive, wh...",5,14-Dec-09,17
3,138000,Ortho Evra,Birth Control,"""This is my first time using any form of birth...",8,3-Nov-15,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""Suboxone has completely turned my life around...",9,27-Nov-16,37
...,...,...,...,...,...,...,...
161292,191035,Campral,Alcohol Dependence,"""I wrote my first report in Mid-October of 201...",10,31-May-15,125
161293,127085,Metoclopramide,Nausea/Vomiting,"""I was given this in IV before surgey. I immed...",1,1-Nov-11,34
161294,187382,Orencia,Rheumatoid Arthritis,"""Limited improvement after 4 months, developed...",2,15-Mar-14,35
161295,47128,Thyroid desiccated,Underactive Thyroid,"""I&#039;ve been on thyroid medication 49 years...",10,19-Sep-15,79
161296,215220,Lubiprostone,"Constipation, Chronic","""I&#039;ve had chronic constipation all my adu...",9,13-Dec-14,116

In [4]:
dataset['review'][15]

'"I have been taking Saxenda since July 2016.  I had severe nausea for about a month once I got up to the 2.6 dosage.  It has since subsided and the only side effect I notice now is the dry mouth.  I make sure to drink  2.5 litres of water a day (about 10 glasses).  This helps with the weight loss as well as the constipation.  I have been reducing my dose to find a comfortable spot where I am still losing weight but don&#039;t feel like I am over medicating.  For me, 1.8 is working very well.  I also feel wearing a Fitbit has really helped.  I can track my food, water, exercise and steps - it keeps me moving more.  When this started I could barely walk the length of myself without getting winded - I have lost 58 lbs so far."'

In [5]:
dataset.shape

(161297, 7)

In [6]:
dataset['drugName'].value_counts()

drugName
Levonorgestrel                       3657
Etonogestrel                         3336
Ethinyl estradiol / norethindrone    2850
Nexplanon                            2156
Ethinyl estradiol / norgestimate     2117
                                     ...
Pacerone                                1
Clemastine                              1
Zemaira                                 1
Riociguat                               1
Calcium carbonate / risedronate         1
Name: count, Length: 3436, dtype: int64

In [7]:
dataset['condition'].value_counts()

condition
Birth Control                                   28788
Depression                                       9069
Pain                                             6145
Anxiety                                          5904
Acne                                             5588
                                                ...
26</span> users found this comment helpful.         1
Patent Ductus Arteriosus                            1
Scleroderma                                         1
145</span> users found this comment helpful.        1
ungal Pneumonia                                     1
Name: count, Length: 884, dtype: int64

In [8]:
dataset['rating'].value_counts()

rating
10    50989
9     27531
1     21619
8     18890
7      9456
5      8013
2      6931
3      6513
6      6343
4      5012
Name: count, dtype: int64

In [9]:
dataset['usefulCount'].value_counts()

usefulCount
2      6391
3      6379
0      6318
4      6258
1      6148
       ...
295       1
328       1
340       1
559       1
267       1
Name: count, Length: 389, dtype: int64

In [10]:
dataset['usefulCount'].max()

1291

In [11]:
dataset.info

<bound method DataFrame.info of         uniqueID                  drugName                     condition  \
0         206461                 Valsartan  Left Ventricular Dysfunction
1          95260                Guanfacine                          ADHD
2          92703                    Lybrel                 Birth Control
3         138000                Ortho Evra                 Birth Control
4          35696  Buprenorphine / naloxone             Opiate Dependence
...          ...                       ...                           ...
161292    191035                   Campral            Alcohol Dependence
161293    127085            Metoclopramide               Nausea/Vomiting
161294    187382                   Orencia          Rheumatoid Arthritis
161295     47128        Thyroid desiccated           Underactive Thyroid
161296    215220              Lubiprostone         Constipation, Chronic

                                                   review  rating       date  \
0       "It has no side effect, I take it in combinati...       9  20-May-12
1       "My son is halfway through his fourth week of ...       8  27-Apr-10
2       "I used to take another oral contraceptive, wh...       5  14-Dec-09
3       "This is my first time using any form of birth...       8   3-Nov-15
4       "Suboxone has completely turned my life around...       9  27-Nov-16
...                                                   ...     ...        ...
161292  "I wrote my first report in Mid-October of 201...      10  31-May-15
161293  "I was given this in IV before surgey. I immed...       1   1-Nov-11
161294  "Limited improvement after 4 months, developed...       2  15-Mar-14
161295  "I&#039;ve been on thyroid medication 49 years...      10  19-Sep-15
161296  "I&#039;ve had chronic constipation all my adu...       9  13-Dec-14

        usefulCount
0                27
1               192
2                17
3                10
4                37
...             ...
161292          125
161293           34
161294           35
161295           79
161296          116

[161297 rows x 7 columns]>

In [12]:
dataset.duplicated().sum()

np.int64(0)

In [13]:
dataset['review'][15].lower()

'"i have been taking saxenda since july 2016.  i had severe nausea for about a month once i got up to the 2.6 dosage.  it has since subsided and the only side effect i notice now is the dry mouth.  i make sure to drink  2.5 litres of water a day (about 10 glasses).  this helps with the weight loss as well as the constipation.  i have been reducing my dose to find a comfortable spot where i am still losing weight but don&#039;t feel like i am over medicating.  for me, 1.8 is working very well.  i also feel wearing a fitbit has really helped.  i can track my food, water, exercise and steps - it keeps me moving more.  when this started i could barely walk the length of myself without getting winded - i have lost 58 lbs so far."'

In [14]:
dataset['review'] = dataset['review'].str.lower()

In [15]:
dataset

,uniqueID,drugName,condition,review,rating,date,usefulCount
0,206461,Valsartan,Left Ventricular Dysfunction,"""it has no side effect, i take it in combinati...",9,20-May-12,27
1,95260,Guanfacine,ADHD,"""my son is halfway through his fourth week of ...",8,27-Apr-10,192
2,92703,Lybrel,Birth Control,"""i used to take another oral contraceptive, wh...",5,14-Dec-09,17
3,138000,Ortho Evra,Birth Control,"""this is my first time using any form of birth...",8,3-Nov-15,10
4,35696,Buprenorphine / naloxone,Opiate Dependence,"""suboxone has completely turned my life around...",9,27-Nov-16,37
...,...,...,...,...,...,...,...
161292,191035,Campral,Alcohol Dependence,"""i wrote my first report in mid-october of 201...",10,31-May-15,125
161293,127085,Metoclopramide,Nausea/Vomiting,"""i was given this in iv before surgey. i immed...",1,1-Nov-11,34
161294,187382,Orencia,Rheumatoid Arthritis,"""limited improvement after 4 months, developed...",2,15-Mar-14,35
161295,47128,Thyroid desiccated,Underactive Thyroid,"""i&#039;ve been on thyroid medication 49 years...",10,19-Sep-15,79
161296,215220,Lubiprostone,"Constipation, Chronic","""i&#039;ve had chronic constipation all my adu...",9,13-Dec-14,116

In [16]:
import string

In [17]:
exclude=string.punctuation

In [18]:
def remove_punc1(text):
    exclude = set(string.punctuation)
    return text.translate(str.maketrans('', '', ''.join(exclude)))

In [19]:
dataset['review'][10000]

'"after much deliberation and many, many meetings, we finally decided to put our 7 year old on low dose abilify. my child is officially diagnosed pdd-nos, which is an autism umbrella disorder. at first the low 2mg dose seemed pretty effective in controlling the anxiety and outburst. however; when our doctor prescribed a higher dose, 5 mg, the exhaustion and weight gain were out of control. my child gained roughly 45 pounds in six months. even when we stopped the medication for the summer months. abilify seems to make my child very hungry, but unable to convert any calories into energy, simply storing all food as fat. we came to the decision that the side effects were out weighing the desired effects, and are trying a new medication. "'

In [20]:
remove_punc1(dataset['review'][10000])

'after much deliberation and many many meetings we finally decided to put our 7 year old on low dose abilify my child is officially diagnosed pddnos which is an autism umbrella disorder at first the low 2mg dose seemed pretty effective in controlling the anxiety and outburst however when our doctor prescribed a higher dose 5 mg the exhaustion and weight gain were out of control my child gained roughly 45 pounds in six months even when we stopped the medication for the summer months abilify seems to make my child very hungry but unable to convert any calories into energy simply storing all food as fat we came to the decision that the side effects were out weighing the desired effects and are trying a new medication '

In [21]:
dataset['review']=dataset['review'].apply(remove_punc1)

In [22]:
import nltk

In [23]:
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [24]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    new_text = []

    for word in text.split():
        if word.lower() not in stop_words:
            new_text.append(word)

    return " ".join(new_text)

In [26]:
remove_stopwords('I write entirely to find out what I\'m thinking, what I see and what it means. What I want and what I fear.')

'write entirely find thinking, see means. want fear.'

In [28]:
dataset['review'] = dataset['review'].apply(remove_stopwords)

In [29]:
dataset['review'][100000]

'medicine terrible fact doctors terrible prescribing thanks 15 min session psychiatrist nodding barely looking writing name pill quotfix mequot face never seen acne thought depressed don039t want even leave house doctors prescribe please trust go herbal neighborhood store get things detox medicine pharmaceutical companies making fortune society believing magic pill sustain life subdue problems you039re smarter right'

In [30]:
from nltk.stem.porter import PorterStemmer

In [31]:
ps = PorterStemmer()

def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [39]:
stem_words('played, playfully, playing')

'played, playfully, play'

In [41]:
dataset['review'] =dataset['review'].apply(stem_words)

In [44]:
dataset['review'][10000]

'much deliber mani mani meet final decid put 7 year old low dose abilifi child offici diagnos pddno autism umbrella disord first low 2mg dose seem pretti effect control anxieti outburst howev doctor prescrib higher dose 5 mg exhaust weight gain control child gain roughli 45 pound six month even stop medic summer month abilifi seem make child hungri unabl convert calori energi simpli store food fat came decis side effect weigh desir effect tri new medic'